name: Update Submit Log

on:
  push:
    paths:
      - 'code/*/*/*'  # Lắng nghe các thay đổi trong thư mục code/{{năm}}_{{tháng}}/{{ngày}}/*

permissions:
  contents: write

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit author name
        id: get_commit_author
        run: |
          # Lấy tên người commit từ Git log
          AUTHOR_NAME=$(git log -1 --pretty=%an)
          echo "AUTHOR_NAME=$AUTHOR_NAME" >> $GITHUB_ENV

      - name: Update submit_log.json
        run: |
          # Đảm bảo tệp docs/challenges/data/submit_log.json tồn tại, nếu không thì tạo mảng rỗng
          if [ ! -f docs/challenges/data/submit_log.json ]; then
            echo '[]' > docs/challenges/data/submit_log.json
          fi

          # Lấy tên người commit và ngày hiện tại
          AUTHOR_NAME="${{ env.AUTHOR_NAME }}"
          CURRENT_DAY=$(date -u +"%d-%m-%Y %H:%M UTC")

          # Đọc dữ liệu hiện tại trong submit_log.json
          DATA=$(cat docs/challenges/data/submit_log.json)

          # Kiểm tra xem ngày đã có trong dữ liệu chưa
          DAY_ENTRY=$(echo "$DATA" | jq -r --arg day "$CURRENT_DAY" \
            'map(select(.day == $day)) | length')

          if [ "$DAY_ENTRY" -gt 0 ]; then
            # Nếu ngày đã có, thêm người commit vào mảng "users"
            jq --arg day "$CURRENT_DAY" --arg name "$AUTHOR_NAME" \
              'map(if .day == $day then .users += [$name] else . end)' \
              docs/challenges/data/submit_log.json > temp.json && mv temp.json docs/challenges/data/submit_log.json
          else
            # Nếu ngày chưa có, thêm mới mục "day" và "users"
            jq --arg day "$CURRENT_DAY" --arg name "$AUTHOR_NAME" \
              '. += [{"day": $day, "users": [$name]}]' \
              docs/challenges/data/submit_log.json > temp.json && mv temp.json docs/challenges/data/submit_log.json
          fi

      - name: Commit and push updated submit_log.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/challenges/data/submit_log.json
          git commit -m "Update submit log with commit author"
          git push
